resources:
- name: amzn-drivers
  type: git
  source:
    branch: master
    uri: https://github.com/mmandolesi-g/amzn-drivers.git

jobs:
- name: build-ena-package
  serial: true
  plan:
  - get: amzn-drivers
    trigger: true
  - task: build-rpm
    config:
      platform: linux
      image_resource:
        type: docker-image
        source:
          repository: paas-docker-artifactory.gannettdigital.com/paas-centos7-base
          tag: "latest"
          insecure_registries: [ "paas-docker-artifactory.gannettdigital.com" ]
      inputs:
        - name: amzn-drivers
      params:
        gdcustom_key: {{gdcustom_key}}
      run:
        path: sh
        args: ['-c', 'cd amzn-drivers && ci/build.sh']